import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  documentationSidebar: [
    "intro",
    { type: "doc", id: "installation", label: "Installation" },
    { type: "doc", id: "getting-started", label: "Getting Started" },
    {
      type: "doc",
      id: "configuration",
      label: "Configuration"
    },
    {
      type: "category",
      label: "Web Components",
      items: [
        "web-components/bike-selector",
        "web-components/bike-selector-banner",
        "web-components/product-result",
        "web-components/collection-result",
        "web-components/compatible-list"
      ]
    },

    {
      type: "doc",
      id: "framework-intergration",
      label: "Framework Intergration"
    }
  ]
};

export default sidebars;
