import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { shopifySidebar } from "./docs/shopify-integration/shopify-integration-sidebar";
import { sdkSidebar } from "./docs/sdk-integration/sdk-integration-sidebar";
import { apiSidebar } from "./docs/api-integration/api-integration-sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  documentationSidebar: [
    "intro",
    { type: "doc", id: "overview", label: "Overview" },
    {
      type: "doc",
      id: "quick-start",
      label: "Quick Start - SDK",
    },
    {
      type: "doc",
      id: "security",
      label: "Security",
    },
    {
      type: "doc",
      id: "multilingual",
      label: "Multilingual Support",
    },
    {
      type: "category",
      label: "Shopify Integration",
      items: [shopifySidebar],
    },
    {
      type: "category",
      label: "SDK Integration",
      items: [sdkSidebar],
    },
    {
      type: "category",
      label: "API Integration",
      items: [apiSidebar],
    },
  ],
};

export default sidebars;
